### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by vktec** [lluchs/vim-wren#1]
Currently, this repository is rather bare. When you view it on GitHub, you're confronted with the source code and nothing else. To make things easier for those new to Vim, it might be a good idea to consider creating a README that looks something like the following:

---

# vim-wren

Vim syntax highlighting for the [Wren][wren] scripting language.

## Installation

With pathogen, run

```bash
git clone https://github.com/lluchs/vim-wren ~/.vim/bundle/vim-wren
```

With vim-plug, add the following to your `~/.vimrc`:

```vim
Plug 'lluchs/vim-wren'
```

With Vundle, add this:

```vim
Plugin 'lluchs/vim-wren'
```

[wren]: http://wren.io/

---

Thanks for the great work on this syntax file, and let me know if you'd like me to submit a PR adding this to the repository!

**Comment by lluchs** [comment]
Thanks!

**Comment by vktec** [comment]
> Thanks!

No problem! I'm happy I was able to help out.

> (getting your name right in the commit needed a force push :x)

Haha!
