### ISSUE TITLE
Nested for isn't highlighted correctly

### ISSUE THREAD

**Issue by avivbeeri** [lluchs/vim-wren#3]
A `for` nested in a `for` loop appears to be highlighted as if it were a function rather than a reserved word.

<img width="449" alt="screen shot 2018-06-30 at 13 19 05" src="https://user-images.githubusercontent.com/1446063/42125116-3599662e-7c68-11e8-9695-ed86938aabac.png">

**Comment by lluchs** [comment]
Looks like I introduced this in <https://github.com/lluchs/vim-wren/commit/bf6f1bba65da71724d0835cf6a0252f3bad72dd8>. There is probably a better way to fix this, but I'm not sure how.
